blank_issues_enabled: true
contact_links:
  - name: Questions & community
    url: https://rayplayer.com
    about: For general questions and help, visit the Ray site / community. Use Issues for bugs and feature requests.
